// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDHsuBj5Bvu14oY3giDv5Eh9b2O4Yxhr7Y',
    appId: '1:123219098668:web:7b83d8fb2352d9fd546589',
    messagingSenderId: '123219098668',
    projectId: 'give-away-dfd3d',
    authDomain: 'give-away-dfd3d.firebaseapp.com',
    storageBucket: 'give-away-dfd3d.appspot.com',
    measurementId: 'G-JXJ9GC6L8N',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAgSmj7lgJ_gNkJaK7yQyOXayBvg9BCqok',
    appId: '1:123219098668:android:3cbee5f40dd80407546589',
    messagingSenderId: '123219098668',
    projectId: 'give-away-dfd3d',
    storageBucket: 'give-away-dfd3d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBOJpwSJrpy4sxU-l4HBA8tU4tYqZD5gk8',
    appId: '1:123219098668:ios:baab3d0de7a0ac09546589',
    messagingSenderId: '123219098668',
    projectId: 'give-away-dfd3d',
    storageBucket: 'give-away-dfd3d.appspot.com',
    androidClientId: '123219098668-a8l9k97e9h2s2bis5oejqlot37ea1ila.apps.googleusercontent.com',
    iosClientId: '123219098668-ucajk6umi269unl4tls26g35qdlag2ht.apps.googleusercontent.com',
    iosBundleId: 'com.example.giveAway',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBOJpwSJrpy4sxU-l4HBA8tU4tYqZD5gk8',
    appId: '1:123219098668:ios:baab3d0de7a0ac09546589',
    messagingSenderId: '123219098668',
    projectId: 'give-away-dfd3d',
    storageBucket: 'give-away-dfd3d.appspot.com',
    androidClientId: '123219098668-a8l9k97e9h2s2bis5oejqlot37ea1ila.apps.googleusercontent.com',
    iosClientId: '123219098668-ucajk6umi269unl4tls26g35qdlag2ht.apps.googleusercontent.com',
    iosBundleId: 'com.example.giveAway',
  );
}
